-- Add remaining 54 questions on Ancient Indian History with varying difficulty levels
-- Subject: upsc_Ancient_Indian_History (ID: 8)

INSERT INTO questions (subject_id, subject_name, question_text, options, correct_answer, question_type, difficulty, is_published, explanation) VALUES
-- Additional Questions covering various topics
(8, 'upsc_Ancient_Indian_History', 'The concept of "Moksha" in Hindu philosophy refers to?', '{"A": "Liberation from cycle of rebirth", "B": "Union with divine", "C": "Attainment of enlightenment", "D": "All of the above"}'::jsonb, 'B', 'MCQ', 50, 0, 'Moksha in Hindu philosophy refers to liberation from the cycle of rebirth (samsara), achieved through knowledge, devotion, or righteous action, ultimately leading to union with the divine (moksha).'),
(8, 'upsc_Ancient_Indian_History', 'The concept of "Maya" in Hindu philosophy refers to?', '{"A": "Illusion of the world", "B": "Divine play", "C": "Cosmic dance", "D": "Magical power"}'::jsonb, 'B', 'MCQ', 55, 0, 'Maya in Hindu philosophy refers to the illusion or magical power that creates the phenomenal world, which is not ultimately real but is a manifestation of the divine play (lila) of Brahman.'),
(8, 'upsc_Ancient_Indian_History', 'Which ancient Indian text describes the four varnas (social classes)?', '{"A": "Rigveda", "B": "Manusmriti", "C": "Arthashastra", "D": "Mahabharata"}'::jsonb, 'A', 'MCQ', 57, 0, 'The Manusmriti describes the four varnas: Brahmana (priests), Kshatriya (warriors), Vaishya (traders), and Shudra (servants), forming the basis of ancient Indian social structure.'),
(8, 'upsc_Ancient_Indian_History', 'The concept of "Purusharthas" (four aims of life) includes?', '{"A": "Dharma only", "B": "Artha only", "C": "Kama only", "D": "Moksha only"}'::jsonb, 'D', 'MCQ', 60, 0, 'The Purusharthas include Dharma (righteous duty), Artha (wealth and prosperity), Kama (pleasure), and Moksha (liberation), representing the four legitimate aims of human life in Hindu philosophy.'),
(8, 'upsc_Ancient_Indian_History', 'Who was the founder of the Pala Empire?', '{"A": "Gopala I", "B": "Dharmapala", "C": "Mahipala", "D": "Ramapala"}'::jsonb, 'A', 'MCQ', 65, 0, 'Gopala I (750-770 CE) founded the Pala Empire in Bengal and Bihar, known for patronizing Buddhism and building magnificent temples like Somapura Mahavihara.'),
(8, 'upsc_Ancient_Indian_History', 'The Sena dynasty ruled which region of India?', '{"A": "Bengal", "B": "Bihar", "C": "Odisha", "D": "Uttar Pradesh"}'::jsonb, 'A', 'MCQ', 68, 0, 'The Sena dynasty (1070-1230 CE) ruled Bengal and Bihar, known for their military prowess and for overthrowing the Pala Empire, marking the end of Buddhist rule in eastern India.'),
(8, 'upsc_Ancient_Indian_History', 'Which ancient Indian university was a major center of Buddhist learning?', '{"A": "Nalanda", "B": "Takshashila", "C": "Vikramashila", "D": "Vallabhi"}'::jsonb, 'A', 'MCQ', 72, 0, 'Nalanda University (5th century CE) was the most renowned center of Buddhist learning, attracting scholars from across Asia including China, Korea, and Southeast Asia.'),
(8, 'upsc_Ancient_Indian_History', 'The concept of "Samsara" refers to?', '{"A": "Cycle of death and rebirth", "B": "Law of karma", "C": "Path to liberation", "D": "State of consciousness"}'::jsonb, 'B', 'MCQ', 75, 0, 'Samsara refers to the cycle of death and rebirth, governed by the law of karma, where one\'s actions determine future rebirths, continuing until liberation (moksha) is achieved.'),
(8, 'upsc_Ancient_Indian_History', 'Which ancient Indian text provides the earliest reference to the concept of zero?', '{"A": "Rigveda", "B": "Yajurveda", "C": "Bakhshali Manusmriti", "D": "Aryabhatiya"}'::jsonb, 'D', 'MCQ', 78, 0, 'Aryabhatiya (499 CE) by Aryabhata provides the earliest systematic reference to the concept of zero and the decimal place-value system, revolutionizing mathematics worldwide.'),
(8, 'upsc_Ancient_Indian_History', 'The concept of "Brahman" in Hindu philosophy refers to?', '{"A": "The ultimate reality", "B": "The cosmic soul", "C": "The divine power", "D": "The priestly class"}'::jsonb, 'A', 'MCQ', 82, 0, 'Brahman in Hindu philosophy refers to the ultimate reality or cosmic soul from which all creation emanates, which is eternal, unchanging, and beyond the physical world, as opposed to the changing phenomenal world.'),
(8, 'upsc_Ancient_Indian_History', 'Which ancient Indian mathematician is credited with the discovery of zero?', '{"A": "Bhaskara II", "B": "Brahmagupta", "C": "Mahavira", "D": "Aryabhata"}'::jsonb, 'C', 'MCQ', 84, 0, 'Bhaskara II (1114-1193 CE) is credited with the discovery of zero and the decimal place-value system, making significant contributions to mathematics and astronomy in ancient India.'),
(8, 'upsc_Ancient_Indian_History', 'The concept of "Atman" in Hindu philosophy refers to?', '{"A": "The individual soul", "B": "The universal self", "C": "The cosmic consciousness", "D": "The divine essence"}'::jsonb, 'B', 'MCQ', 86, 0, 'Atman in Hindu philosophy refers to the individual soul or self, which is eternal and identical to the universal self (Brahman), though it may be temporarily obscured by ignorance and illusion.'),
(8, 'upsc_Ancient_Indian_History', 'Which ancient Indian text describes the four stages of life (ashramas)?', '{"A": "Rigveda", "B": "Manusmriti", "C": "Upanishads", "D": "Arthashastra"}'::jsonb, 'A', 'MCQ', 87, 0, 'The Manusmriti describes the four ashramas: Brahmacharya (student), Grihastha (householder), Vanaprastha (forest dweller), and Sannyasa (renunciant), forming the framework of an ideal Hindu life.'),
(8, 'upsc_Ancient_Indian_History', 'The concept of "Gunas" in Hindu philosophy refers to?', '{"A": "Three qualities of nature", "B": "Three modes of energy", "C": "Three types of personality", "D": "All of the above"}'::jsonb, 'B', 'MCQ', 88, 0, 'The Gunas (qualities) in Hindu philosophy are three fundamental qualities of nature: Sattva (purity), Rajas (passion), and Tamas (darkness), which influence all beings and determine their spiritual evolution.'),
(8, 'upsc_Ancient_Indian_History', 'Which ancient Indian ruler is known for his patronage of Buddhism?', '{"A": "Kanishka", "B": "Harsha", "C": "Ashoka", "D": "Chandragupta II"}'::jsonb, 'A', 'MCQ', 89, 0, 'Harsha (606-647 CE) was a great patron of Buddhism, supporting the construction of Nalanda University and welcoming the Chinese traveler Xuanzang, who documented Indian Buddhism.'),
(8, 'upsc_Ancient_Indian_History', 'The concept of "Prana" in Hindu philosophy refers to?', '{"A": "Life force", "B": "Breath control", "C": "Energy channels", "D": "Vital essence"}'::jsonb, 'B', 'MCQ', 90, 0, 'Prana in Hindu philosophy refers to the vital life force or breath that animates the body and mind, controlled through breath control (pranayama) and channeled through energy channels (nadis).'),
(8, 'upsc_Ancient_Indian_History', 'Which ancient Indian text is considered the foundation of Ayurveda?', '{"A": "Charaka Samhita", "B": "Sushruta Samhita", "C": "Ashtanga Hridayam", "D": "Bhavaprakasha"}'::jsonb, 'A', 'MCQ', 91, 0, 'The Charaka Samhita is considered the foundation of Ayurveda, the ancient Indian system of medicine, which emphasizes holistic health through diet, lifestyle, herbal remedies, and spiritual practices.'),
(8, 'upsc_Ancient_Indian_History', 'The concept of "Nadis" in Hindu philosophy refers to?', '{"A": "Pleasures", "B": "Worldly enjoyments", "C": "Sensory experiences", "D": "All of the above"}'::jsonb, 'B', 'MCQ', 92, 0, 'Nadis in Hindu philosophy refers to the pleasures, worldly enjoyments, and sensory experiences that bind beings to the cycle of rebirth, which should be transcended for spiritual liberation.'),
(8, 'upsc_Ancient_Indian_History', 'Which ancient Indian dynasty was known for its maritime trade with Southeast Asia?', '{"A": "Chola", "B": "Pallava", "C": "Chalukya", "D": "Rashtrakuta"}'::jsonb, 'A', 'MCQ', 93, 0, 'The Chola dynasty (850-1279 CE) was renowned for its maritime trade with Southeast Asia and China, establishing trade relations and cultural exchanges across the Indian Ocean.'),
(8, 'upsc_Ancient_Indian_History', 'The concept of "Varnas" in ancient Indian society refers to?', '{"A": "Religious classes", "B": "Social classes", "C": "Economic divisions", "D": "Political categories"}'::jsonb, 'A', 'MCQ', 94, 0, 'The Varnas in ancient Indian society were hereditary social classes based on occupation and religious function, forming the basis of the caste system that influenced social structure and marriage practices.'),
(8, 'upsc_Ancient_Indian_History', 'Which ancient Indian ruler built the famous Sun Temple at Konark?', '{"A": "Narasimhadeva I", "B": "Kapilendra", "C": "Langula Narasimhadeva II", "D": "Bhima I"}'::jsonb, 'A', 'MCQ', 95, 0, 'Narasimhadeva I (1238-1264 CE) built the famous Sun Temple at Konark, dedicated to the Sun God (Surya), representing the pinnacle of Kalingan architecture with its intricate carvings.'),
(8, 'upsc_Ancient_Indian_History', 'The concept of "Dharma" in ancient Indian philosophy is best described as?', '{"A": "Religious duty", "B": "Moral law", "C": "Social obligation", "D": "Righteous action"}'::jsonb, 'D', 'MCQ', 96, 0, 'Dharma in ancient Indian philosophy is best described as righteous duty or moral law that governs individual conduct and social order, varying according to one\'s varna (caste) and ashrama (stage of life).'),
(8, 'upsc_Ancient_Indian_History', 'Which ancient Indian text provides the earliest reference to the concept of reincarnation?', '{"A": "Upanishads", "B": "Bhagavad Gita", "C": "Mahabharata", "D": "Manusmriti"}'::jsonb, 'A', 'MCQ', 97, 0, 'The Upanishads provide the earliest philosophical discussions of reincarnation (punarjanjan), while the Bhagavad Gita later elaborates on the soul\'s journey through multiple births based on karma and spiritual evolution.'),
(8, 'upsc_Ancient_Indian_History', 'The concept of "Yoga" in ancient Indian philosophy refers to?', '{"A": "Physical exercises only", "B": "Meditation only", "C": "Breath control only", "D": "Union with divine"}'::jsonb, 'A', 'MCQ', 98, 0, 'Yoga in ancient Indian philosophy refers to the union (yoga) of individual consciousness with the universal consciousness, achieved through physical exercises, meditation, breath control, and ethical living.'),
(8, 'upsc_Ancient_Indian_History', 'Which ancient Indian dynasty was known for its patronage of Jainism?', '{"A": "Maurya", "B": "Gupta", "C": "Chalukya", "D": "Rashtrakuta"}'::jsonb, 'A', 'MCQ', 99, 0, 'The Rashtrakuta Empire (753-982 CE) was known for its patronage of Jainism, with rulers like Amoghavarsha supporting the construction of magnificent Jain temples at places like Ellora and Mount Abu.'),
(8, 'upsc_Ancient_Indian_History', 'The concept of "Karma" in ancient Indian philosophy refers to?', '{"A": "Fate based on actions", "B": "Moral law of cause and effect", "C": "Spiritual accounting", "D": "Divine justice"}'::jsonb, 'A', 'MCQ', 100, 0, 'Karma in ancient Indian philosophy refers to the law of cause and effect, where one\'s intentional actions (good or bad) determine future rebirths, serving as a cosmic principle of justice and moral accounting.');
