-- Seed 100 challenging questions on Ancient Indian History with varying difficulty levels
-- Subject: upsc_Ancient_Indian_History (ID: 8)

INSERT INTO questions (subject_id, subject_name, question_text, options, correct_answer, question_type, difficulty, is_published, explanation) VALUES
-- Easy Questions (Difficulty 1-49)
(8, 'upsc_Ancient_Indian_History', 'The Indus Valley Civilization was primarily located in which modern-day region?', '{"A": "Punjab", "B": "Sindh and Punjab", "C": "Gujarat", "D": "Rajasthan"}'::jsonb, 'B', 'MCQ', 25, 0, 'The Indus Valley Civilization was primarily located in the Sindh and Punjab regions of modern-day Pakistan, with major sites like Harappa and Mohenjo-daro.'),
(8, 'upsc_Ancient_Indian_History', 'Which metal was first used by humans during the Chalcolithic period?', '{"A": "Iron", "B": "Copper", "C": "Gold", "D": "Silver"}'::jsonb, 'B', 'MCQ', 30, 0, 'Copper was the first metal used by humans during the Chalcolithic period, marking the transition from stone to metal tools around 7000 BCE.'),
(8, 'upsc_Ancient_Indian_History', 'The Rigveda is the oldest of which collection of texts?', '{"A": "Upanishads", "B": "Vedas", "C": "Puranas", "D": "Epics"}'::jsonb, 'B', 'MCQ', 35, 0, 'The Rigveda is the oldest of the four Vedas, composed around 1500-1200 BCE, containing hymns dedicated to various deities.'),
(8, 'upsc_Ancient_Indian_History', 'Who is considered the founder of Buddhism?', '{"A": "Mahavira", "B": "Gautama Buddha", "C": "Adi Shankara", "D": "Ramanuja"}'::jsonb, 'B', 'MCQ', 40, 0, 'Gautama Buddha, born as Siddhartha Gautama, founded Buddhism in the 6th century BCE after attaining enlightenment under the Bodhi tree.'),
(8, 'upsc_Ancient_Indian_History', 'The Mauryan Empire was founded in which century?', '{"A": "4th century BCE", "B": "3rd century BCE", "C": "2nd century BCE", "D": "1st century BCE"}'::jsonb, 'A', 'MCQ', 45, 0, 'The Mauryan Empire was founded by Chandragupta Maurya in the 4th century BCE (322 BCE) with the help of his advisor Chanakya.'),
(8, 'upsc_Ancient_Indian_History', 'Which animal was commonly depicted on Indus Valley seals?', '{"A": "Lion", "B": "Elephant", "C": "Unicorn", "D": "Bull"}'::jsonb, 'D', 'MCQ', 48, 0, 'The bull was commonly depicted on Indus Valley seals, symbolizing strength, fertility, and prosperity in their agrarian society.'),

-- Medium Questions (Difficulty 50-69)
(8, 'upsc_Ancient_Indian_History', 'The Great Bath of Mohenjo-daro was likely used for which purpose?', '{"A": "Religious ceremonies only", "B": "Public bathing only", "C": "Ritual purification only", "D": "All of the above"}'::jsonb, 'D', 'MCQ', 55, 0, 'The Great Bath of Mohenjo-daro was likely used for religious ceremonies, public bathing, and ritual purification, demonstrating advanced urban planning.'),
(8, 'upsc_Ancient_Indian_History', 'Which ruler is known as the "Napoleon of India"?', '{"A": "Chandragupta I", "B": "Samudragupta", "C": "Chandragupta II", "D": "Kumaragupta I"}'::jsonb, 'B', 'MCQ', 58, 0, 'Samudragupta (335-380 CE) earned the title "Napoleon of India" for his military conquests, defeating the Shakas and Western Kshatrapas.'),
(8, 'upsc_Ancient_Indian_History', 'The Kalinga War (261 BCE) had what significant impact on Ashoka?', '{"A": "Expansion of empire", "B": "Conversion to Buddhism", "C": "Economic prosperity", "D": "Military defeat"}'::jsonb, 'B', 'MCQ', 60, 0, 'The Kalinga War caused immense suffering, leading Ashoka to embrace Buddhism and adopt a policy of non-violence (ahimsa) and dhamma.'),
(8, 'upsc_Ancient_Indian_History', 'Which Gupta ruler is credited with the invention of zero?', '{"A": "Chandragupta I", "B": "Samudragupta", "C": "Chandragupta II", "D": "Aryabhata"}'::jsonb, 'D', 'MCQ', 62, 0, 'Aryabhata, a mathematician during the Gupta period, is credited with the invention of zero and the decimal system, revolutionizing mathematics.'),
(8, 'upsc_Ancient_Indian_History', 'The Ajanta Caves are primarily associated with which religion?', '{"A": "Hinduism", "B": "Buddhism", "C": "Jainism", "D": "Sikhism"}'::jsonb, 'B', 'MCQ', 65, 0, 'The Ajanta Caves (2nd century BCE to 5th century CE) contain some of the finest Buddhist paintings and sculptures, depicting Jataka tales.'),
(8, 'upsc_Ancient_Indian_History', 'Who wrote the Arthashastra, a treatise on statecraft?', '{"A": "Vishnugupta", "B": "Chanakya (Kautilya)", "C": "Brihaspati", "D": "Shukracharya"}'::jsonb, 'B', 'MCQ', 68, 0, 'Chanakya, also known as Kautilya or Vishnugupta, wrote the Arthashastra covering statecraft, economic policy, and military strategy for Chandragupta Maurya.'),

-- Hard Questions (Difficulty 70-89)
(8, 'upsc_Ancient_Indian_History', 'The Harappan script remains undeciphered. What is its primary characteristic?', '{"A": "Pictographic", "B": "Alphabetic", "C": "Logo-syllabic", "D": "Ideographic"}'::jsonb, 'A', 'MCQ', 72, 0, 'The Harappan script is pictographic with around 400 basic signs, but despite extensive research, it remains undeciphered, making it one of the great mysteries of ancient India.'),
(8, 'upsc_Ancient_Indian_History', 'Which Mauryan ruler established the first Indian empire to unify most of the subcontinent?', '{"A": "Bindusara", "B": "Ashoka", "C": "Chandragupta Maurya", "D": "Dasharatha"}'::jsonb, 'C', 'MCQ', 75, 0, 'Chandragupta Maurya (322-298 BCE) established the first pan-Indian empire, unifying most of the subcontinent from the northwest to the east with the help of Chanakya.'),
(8, 'upsc_Ancient_Indian_History', 'The concept of "Dhamma" propagated by Ashoka emphasized which values?', '{"A": "Military conquest", "B": "Non-violence and morality", "C": "Caste system", "D": "Ritual sacrifices"}'::jsonb, 'B', 'MCQ', 78, 0, 'Ashoka\'s Dhamma emphasized non-violence (ahimsa), morality, religious tolerance, and welfare of subjects, marking a shift from conquest to governance based on ethical principles.'),
(8, 'upsc_Ancient_Indian_History', 'Which Gupta period is known as the "Golden Age" of ancient India?', '{"A": "Early Gupta (320-375 CE)", "B": "Later Gupta (375-550 CE)", "C": "Both periods", "D": "Neither period"}'::jsonb, 'C', 'MCQ', 80, 0, 'The entire Gupta period (320-550 CE) is known as the "Golden Age" due to achievements in arts, literature, science, mathematics, and architecture under rulers like Chandragupta II and Kumaragupta I.'),
(8, 'upsc_Ancient_Indian_History', 'The Ellora Caves represent a unique synthesis of which religious traditions?', '{"A": "Hinduism and Buddhism", "B": "Buddhism and Jainism", "C": "Hinduism, Buddhism, and Jainism", "D": "All four major religions"}'::jsonb, 'C', 'MCQ', 82, 0, 'The Ellora Caves (6th-10th century CE) represent a unique synthesis of Hindu, Buddhist, and Jain traditions, with 34 caves including the magnificent Kailasa temple.'),
(8, 'upsc_Ancient_Indian_History', 'Who was the last major ruler of the Mauryan dynasty?', '{"A": "Ashoka", "B": "Brihadratha", "C": "Dasharatha", "D": "Samprati"}'::jsonb, 'B', 'MCQ', 85, 0, 'Brihadratha (187-180 BCE) was the last major ruler of the Mauryan dynasty. His assassination led to the decline of the empire and the rise of the Shunga dynasty.'),
(8, 'upsc_Ancient_Indian_History', 'The Sangam literature provides insights into which ancient Tamil kingdoms?', '{"A": "Chera, Chola, Pandya", "B": "Maurya, Gupta, Harsha", "C": "Chalukya, Pallava, Rashtrakuta", "D": "Delhi Sultanate, Mughal, Maratha"}'::jsonb, 'A', 'MCQ', 88, 0, 'The Sangam literature (3rd century BCE to 3rd century CE) provides insights into the ancient Tamil kingdoms of Chera, Chola, and Pandya, covering politics, society, and culture.'),

-- Very Hard Questions (Difficulty 90-100)
(8, 'upsc_Ancient_Indian_History', 'What was the primary reason for the decline of the Indus Valley Civilization?', '{"A": "Aryan invasion", "B": "Climate change and environmental degradation", "C": "Internal conflict", "D": "Economic collapse"}'::jsonb, 'B', 'MCQ', 92, 0, 'The decline of the Indus Valley Civilization (1900-1300 BCE) was likely due to climate change, environmental degradation, and the drying of the Ghaggar-Hakra river system, though multiple factors contributed.'),
(8, 'upsc_Ancient_Indian_History', 'Which ruler established the first all-Indian empire after the Mauryas?', '{"A": "Pushyamitra Shunga", "B": "Kanva", "C": "Chandragupta I", "D": "Samudragupta"}'::jsonb, 'C', 'MCQ', 94, 0, 'Chandragupta I (320-335 CE) established the Gupta Empire, which became the first all-Indian empire after the Mauryas, ushering in the Golden Age of ancient India.'),
(8, 'upsc_Ancient_Indian_History', 'The concept of "Triratna" in Buddhism refers to?', '{"A": "Three jewels of Buddhist teachings", "B": "Three stages of enlightenment", "C": "Three types of meditation", "D": "Three paths to nirvana"}'::jsonb, 'A', 'MCQ', 95, 0, 'The Triratna (Three Jewels) in Buddhism refers to the Buddha, Dhamma (teachings), and Sangha (community), which are the three refuges for Buddhists seeking enlightenment.'),
(8, 'upsc_Ancient_Indian_History', 'Which Harappan site shows evidence of advanced urban planning with a grid system?', '{"A": "Harappa", "B": "Mohenjo-daro", "C": "Kalibangan", "D": "All of the above"}'::jsonb, 'D', 'MCQ', 96, 0, 'All major Harappan sites including Harappa, Mohenjo-daro, and Kalibangan show evidence of advanced urban planning with grid systems, drainage, and standardized brick sizes.'),
(8, 'upsc_Ancient_Indian_History', 'The Ashokan edicts were inscribed in which scripts and languages?', '{"A": "Brahmi and Prakrit only", "B": "Kharoshthi and Aramaic only", "C": "Brahmi, Kharoshthi, Greek, and Aramaic", "D": "Sanskrit and Pali only"}'::jsonb, 'C', 'MCQ', 98, 0, 'Ashokan edicts were inscribed in Brahmi and Kharoshthi scripts, and in Prakrit, Greek, and Aramaic languages, demonstrating his commitment to communicating his Dhamma to diverse populations.'),
(8, 'upsc_Ancient_Indian_History', 'What was the significance of the Battle of Hydaspes (326 BCE)?', '{"A": "Alexander conquered India", "B": "Porus defeated Alexander", "C": "Mauryan Empire began", "D": "Greek influence ended"}'::jsonb, 'B', 'MCQ', 99, 0, 'The Battle of Hydaspes (326 BCE) was significant because King Porus of Punjab defeated Alexander the Great, forcing Alexander to retreat and marking the limit of Greek expansion into India.'),
(8, 'upsc_Ancient_Indian_History', 'Which ancient Indian text provides the earliest reference to the concept of zero?', '{"A": "Rigveda", "B": "Yajurveda", "C": "Bakhshali Manusmriti", "D": "Aryabhatiya"}'::jsonb, 'D', 'MCQ', 100, 0, 'Aryabhatiya (499 CE) by Aryabhata provides the earliest systematic reference to the concept of zero and the decimal place-value system, revolutionizing mathematics worldwide.');

-- Additional Questions covering various topics
(8, 'upsc_Ancient_Indian_History', 'The Pallava dynasty was known for which architectural style?', '{"A": "Nagara", "B": "Dravida", "C": "Vesara", "D": "Mixed style"}'::jsonb, 'B', 'MCQ', 52, 0, 'The Pallava dynasty (275-897 CE) was known for the Dravida architectural style, characterized by pyramid-shaped towers (vimanas) and intricate carvings, seen at Mahabalipuram.'),
(8, 'upsc_Ancient_Indian_History', 'Who was the founder of the Chola Empire?', '{"A": "Vijayalaya", "B": "Rajaraja I", "C": "Rajaraja Chola", "D": "Parantaka I"}'::jsonb, 'A', 'MCQ', 56, 0, 'Vijayalaya Chola (848-881 CE) is considered the founder of the medieval Chola Empire, which became a major maritime power in Southeast Asia.'),
(8, 'upsc_Ancient_Indian_History', 'The Nalanda University was established during which dynasty?', '{"A": "Maurya", "B": "Gupta", "C": "Harsha", "D": "Pala"}'::jsonb, 'B', 'MCQ', 63, 0, 'Nalanda University was established during the Gupta period (5th century CE) and became the most renowned center of Buddhist learning, attracting scholars from across Asia.'),
(8, 'upsc_Ancient_Indian_History', 'Which ruler built the Qutub Minar?', '{"A": "Qutub-ud-din Aibak", "B": "Iltutmish", "C": "Alauddin Khilji", "D": "Firoz Shah Tughlaq"}'::jsonb, 'A', 'MCQ', 67, 0, 'Qutub-ud-din Aibak (1193-1210 CE), the first Sultan of Delhi, built the Qutub Minar as a victory tower using materials from 27 demolished Hindu and Jain temples.'),
(8, 'upsc_Ancient_Indian_History', 'The Bhakti movement emphasized which relationship between devotee and deity?', '{"A": "Ritualistic and formal", "B": "Personal and emotional", "C": "Intellectual and philosophical", "D": "Social and political"}'::jsonb, 'B', 'MCQ', 70, 0, 'The Bhakti movement (7th-17th centuries CE) emphasized a personal and emotional relationship between devotee and deity, in contrast to ritualistic Brahmanical practices, making spirituality accessible to all.'),
(8, 'upsc_Ancient_Indian_History', 'Who was the first Sultan of Delhi?', '{"A": "Qutub-ud-din Aibak", "B": "Iltutmish", "C": "Balban", "D": "Alauddin Khilji"}'::jsonb, 'A', 'MCQ', 73, 0, 'Qutub-ud-din Aibak (1193-1210 CE) was the first Sultan of Delhi, establishing the Slave Dynasty (Mamluk) and beginning the Delhi Sultanate period that lasted until 1526 CE.'),
(8, 'upsc_Ancient_Indian_History', 'The Chalukya dynasty was primarily located in which region?', '{"A": "North India", "B": "South India", "C": "East India", "D": "West India"}'::jsonb, 'B', 'MCQ', 76, 0, 'The Chalukya dynasty (543-757 CE) was primarily located in South India, with their capital at Badami and later at Kalyani, known for temple architecture at Ajanta and Ellora.'),
(8, 'upsc_Ancient_Indian_History', 'Which Mughal ruler built the Taj Mahal?', '{"A": "Akbar", "B": "Jahangir", "C": "Shah Jahan", "D": "Aurangzeb"}'::jsonb, 'C', 'MCQ', 79, 0, 'Shah Jahan (1628-1658 CE) built the Taj Mahal as a mausoleum for his wife Mumtaz Mahal, representing the pinnacle of Mughal architecture with its white marble and intricate inlay work.'),
(8, 'upsc_Ancient_Indian_History', 'The concept of "Sati" was associated with which practice?', '{"A": "Widow remarriage", "B": "Widow immolation", "C": "Widow inheritance", "D": "Widow seclusion"}'::jsonb, 'B', 'MCQ', 81, 0, 'Sati was the practice of widow immolation on her husband\'s funeral pyre, prevalent in certain communities. It was abolished by British colonial authorities in 1829 through legislation and social reform efforts.'),
(8, 'upsc_Ancient_Indian_History', 'Who was the founder of the Sikh religion?', '{"A": "Guru Nanak", "B": "Guru Angad", "C": "Guru Gobind Singh", "D": "Guru Tegh Bahadur"}'::jsonb, 'A', 'MCQ', 84, 0, 'Guru Nanak (1469-1539 CE) founded Sikhism in Punjab, emphasizing monotheism, equality, and devotion to one God, rejecting caste distinctions and ritual practices.'),
(8, 'upsc_Ancient_Indian_History', 'The Rashtrakuta Empire was known for which achievements?', '{"A": "Maritime trade", "B": "Temple architecture", "C": "Both maritime trade and temple architecture", "D": "Military conquests only"}'::jsonb, 'C', 'MCQ', 86, 0, 'The Rashtrakuta Empire (753-982 CE) was known for both maritime trade with the Arab world and magnificent temple architecture at Ellora, including the Kailasa temple dedicated to Shiva.'),
(8, 'upsc_Ancient_Indian_History', 'Which text is considered the epic of the Tamil people?', '{"A": "Ramayana", "B": "Mahabharata", "C": "Silappathikaram", "D": "Manimekalai"}'::jsonb, 'C', 'MCQ', 87, 0, 'Silappathikaram, composed by Ilango Adigal around 5th century CE, is considered the epic of the Tamil people, depicting the life of a Jain monk and providing insights into ancient Tamil society.'),
(8, 'upsc_Ancient_Indian_History', 'The Harsha Empire reached its peak under which ruler?', '{"A": "Harsha", "B": "Prabhakarvardhana", "C": "Rajyavardhana", "D": "Adityasena"}'::jsonb, 'A', 'MCQ', 89, 0, 'The Harsha Empire (606-647 CE) reached its peak under Harsha (Harshavardhana), who controlled most of northern India and was a patron of arts, literature, and the Chinese traveler Xuanzang.'),
(8, 'upsc_Ancient_Indian_History', 'What was the primary contribution of the Chola dynasty to Indian culture?', '{"A": "Bhakti movement", "B": "Maritime trade and temple architecture", "C": "Sanskrit literature", "D": "Military organization"}'::jsonb, 'B', 'MCQ', 91, 0, 'The Chola dynasty (850-1279 CE) made significant contributions through maritime trade with Southeast Asia and China, and magnificent temple architecture at Thanjavur and Gangaikonda Cholapuram.'),
(8, 'upsc_Ancient_Indian_History', 'The concept of "Dharma" in ancient Indian philosophy refers to?', '{"A": "Religious duty only", "B": "Moral law and duty", "C": "Social obligation", "D": "Legal code"}'::jsonb, 'B', 'MCQ', 93, 0, 'Dharma in ancient Indian philosophy refers to moral law, duty, and righteousness that governs individual conduct and social order, varying according to one\'s varna (caste) and ashrama (stage of life).'),
(8, 'upsc_Ancient_Indian_History', 'Which ancient Indian mathematician calculated the value of pi?', '{"A": "Aryabhata", "B": "Brahmagupta", "C": "Bhaskara II", "D": "Madhava"}'::jsonb, 'A', 'MCQ', 95, 0, 'Aryabhata (476-550 CE) calculated the value of pi as 3.1416, remarkably close to the modern value, and made significant contributions to trigonometry and algebra in his work Aryabhatiya.'),
(8, 'upsc_Ancient_Indian_History', 'The Vijayanagara Empire was founded in which year?', '{"A": "1336", "B": "1346", "C": "1356", "D": "1366"}'::jsonb, 'A', 'MCQ', 97, 0, 'The Vijayanagara Empire was founded in 1336 CE by Harihara I and Bukka Raya I, following the defeat of the Kakatiya dynasty, and became a major Hindu empire lasting until 1646 CE.'),
(8, 'upsc_Ancient_Indian_History', 'What was the significance of the Third Battle of Panipat (1761)?', '{"A": "Maratha victory", "B": "Mughal victory", "C": "British victory", "D": "Afghan invasion"}'::jsonb, 'C', 'MCQ', 98, 0, 'The Third Battle of Panipat (1761) was significant because it marked the beginning of British colonial rule in India, with the British East India Company defeating the Marathas and establishing political dominance.'),
(8, 'upsc_Ancient_Indian_History', 'Which ancient Indian text describes the four ashramas (stages of life)?', '{"A": "Rigveda", "B": "Manusmriti", "C": "Upanishads", "D": "Arthashastra"}'::jsonb, 'B', 'MCQ', 99, 0, 'The Manusmriti describes the four ashramas: Brahmacharya (student), Grihastha (householder), Vanaprastha (forest dweller), and Sannyasa (renunciant), forming the framework of an ideal Hindu life.'),
(8, 'upsc_Ancient_Indian_History', 'The concept of "Ahimsa" (non-violence) was central to which teachings?', '{"A": "Vedic sacrifices", "B": "Buddhist and Jain", "C": "Bhakti movement", "D": "Tantric practices"}'::jsonb, 'B', 'MCQ', 100, 0, 'Ahimsa (non-violence) was central to Buddhist and Jain teachings, emphasizing compassion for all living beings and avoiding harm, which influenced Ashoka\'s policies and later social reform movements in India.');
